### PR TITLE
Increase publication size to include compression

### PR DESCRIPTION
**Pull request by Sohamdg081992**
This change pessimistically sets limit of maxPublicationPackageSizeInBytes to 5000000 to include compression in order to support higher cardinality metrics.

I have deployed the image in scale cluster and have tested the replicaset. There are no restarts, errors in the logs, metrics are flowing in Grafana. I am attaching the CPU and memory usage metrics for the replicaset at the deployment, workload and pod level for evidence. They look good.
MicrosoftTeams-image (7)
MicrosoftTeams-image (6)
MicrosoftTeams-image (5)
MicrosoftTeams-image (4)
MicrosoftTeams-image (3)
MicrosoftTeams-image (2)

### CODE REVIEW

**Comment by gracewehner** [comment]
Thanks Soham, looks good. Do you have screenshots for the cpu and memory of the older agent version that was running on the cluster?

**Comment by Sohamdg081992** [comment]
> Thanks Soham, looks good. Do you have screenshots for the cpu and memory of the older agent version that was running on the cluster?

Hi Grace, I do not have the screenshots of the older agent. As I remember, it was an old agent(around 6.4.0). Should I mount the latest released image 6.7.2-main-06-26-2023-6ee07896 and share the screenshots for comparison?

**Comment by gracewehner** [comment]
> > Thanks Soham, looks good. Do you have screenshots for the cpu and memory of the older agent version that was running on the cluster?
> 
> Hi Grace, I do not have the screenshots of the older agent. As I remember, it was an old agent(around 6.4.0). Should I mount the latest released image 6.7.2-main-06-26-2023-6ee07896 and share the screenshots for comparison?

Yes that would be great!

**Comment by Sohamdg081992** [comment]
> This change pessimistically sets limit of maxPublicationPackageSizeInBytes to 5000000 to include compression in order to support higher cardinality metrics.
> 
> I have deployed the image in scale cluster and have tested the replicaset. There are no restarts, errors in the logs, metrics are flowing in Grafana. I am attaching the CPU and memory usage metrics for the replicaset at the deployment, workload and pod level for evidence. They look good.

Hi Grace, I created a new pr https://github.com/Azure/prometheus-collector/pull/537 because I merged some unwanted changes to this and could not git revert it somehow. I have added the screenshots. Thanks!

**Pull request closed without merging**
