### PR TITLE
fix: update prometheus.rules.json with new schema

### PR DESCRIPTION
**Pull request by monteiro-renato**
Related with > https://github.com/SchemaStore/schemastore/pull/4148

### CODE REVIEW

**Comment by vishiy** [comment]
Thanks for your PR @monteiro-renato .

**Comment by vishiy** [comment]
@moshemal - can one of you validate this data type addition for expr and approve, after which we can merge ?

**Comment by monteiro-renato** [comment]
@microsoft-github-policy-service agree

**Comment by monteiro-renato** [comment]
Hey @vishiy 👋, 

I've encountered another error but this time with the azure-sdk-for-go [armalertsmanagement.PrometheusRule](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/alertsmanagement/armalertsmanagement@v0.10.0#PrometheusRule) struct which expects a pointer to a string only.

It would be nice if the Expression field was consistent across projects.

Not sure if this is something you can raise internally or if I should open a ticket directly on the azure-sdk-for-go repo?

**Comment by monteiro-renato** [comment]
Still interested but awaiting feedback from codeowners.

**Comment by monteiro-renato** [comment]
I noticed a new PR will fix the tests > https://github.com/Azure/prometheus-collector/pull/1008 so I reverted my changes and this PR will only have the changes to the schema.

**Comment by monteiro-renato** [comment]
Still interested but awaiting feedback from codeowners.

**Comment by vishiy** [comment]
@moshemal - please check and review the schema changes and add Noam if needed...

**Comment by monteiro-renato** [comment]
Hey 👋 
I've added both changes I suggested to my own fork last week and I saw no issues deploying the ARM templates: https://github.com/monteiro-renato/prometheus-collector/tree/with-piped-input.

Here's an example of what I was trying to deploy initially and failing due to the schema only accepting strings in the expr field:
bilde
Not sure how testing is done on your side but you can add a test where the expression field in the prometheus rule is a number instead of a string and see how it goes.

**Review by moshemal — APPROVED** [review]

**Comment by monteiro-renato** [comment]
@vishiy, any idea why CI is failing?

**Comment by vishiy** [comment]
> @vishiy, any idea why CI is failing?

Hi @monteiro-renato - permissions issue. i will create a branch off of your pr and then merge soon after a few other merges. apologies for the delay.

**Comment by vishiy** [comment]
https://github.com/Azure/prometheus-collector/pull/1026

**Comment by monteiro-renato** [comment]
Thx, Looks like it's all green now.
I will close this one then.

**Comment by vishiy** [comment]
> Thx, Looks like it's all green now. I will close this one then.

thank you!

**Pull request closed without merging**
