### PR TITLE
[fix] Fix the fluent bit error when collector health is enabled

### PR DESCRIPTION
**Pull request by Sohamdg081992**
This change fixes the fluent bit error when prometheus collector health is enabled.
This change adds a CVE based on otelcollector.

AKS [Cluster](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/1a3fd8b1-7a92-4730-8e47-dec9e67f49a9/resourceGroups/testrecalertswcussoham/providers/Microsoft.ContainerService/managedClusters/TestRecAlertsWcusSoham/overview) with setup and updated image

The below error which was showing up when collector health was enabled.

`
panic: http: multiple registrations for /metrics goroutine 36 [running]: net/http.(*ServeMux).Handle(0x7f5fe41bd440, {0x7f5fe3131dba, 0x8}, {0x7f5fe36a7820?, 0xc0000de750}) /usr/local/go/src/net/http/server.go:2503 +0x239 net/http.Handle(...) /usr/local/go/src/net/http/server.go:2546 main.ExposePrometheusCollectorHealthMetrics() /src/prometheus_collector_health.go:100 +0x307 created by main.FLBPluginInit /src/out_appinsights.go:41 +0xc9
`

Below are screenshots ;

Health is enabled
CollectorHealth

Svc & Pod monitors attached

Podmontr
SvcMon

Telemetry is flowing for all plugins
MECpu
MEmem
nonta
OtelCpu
OtelMem
otelmem1
targetallocator

No errors in logs

image

### CODE REVIEW

**Comment by gracewehner** [comment]
Thanks Soham! Could you also enable prometheus-collector-health on our ci/cd dev cluster for this merge by changing the file:
`otelcollector/test/test-cluster-yamls/configmaps/ama-metrics-settings-configmap.yaml` to have `prometheuscollectorhealth = true`?

**Review by rashmichandrashekar — APPROVED** [review]

**Comment by rashmichandrashekar** [comment]
@Sohamdg081992 - LGTM. pls remove white line changes from the build file.

**Comment by Sohamdg081992** [comment]
> @Sohamdg081992 - LGTM. pls remove white line changes from the build file.

Sure. Thanks Rashmi! Will do.

**Comment by Sohamdg081992** [comment]
> Thanks Soham! Could you also enable prometheus-collector-health on our ci/cd dev cluster for this merge by changing the file: `otelcollector/test/test-cluster-yamls/configmaps/ama-metrics-settings-configmap.yaml` to have `prometheuscollectorhealth = true`?

Sure. Thanks Grace! Will do.

**Review by gracewehner — APPROVED** [review]

**Comment by Sohamdg081992** [comment]
Closing this PR in favour of this https://github.com/Azure/prometheus-collector/pull/841 because git history got corrupted while trying to remove a file change(whitespace).

**Pull request closed without merging**
