### PR TITLE
add remaining sdl scans similar to onebranch default

### PR DESCRIPTION
**Pull request by Sohamdg081992**
Add the remaining SDL scans based on Official build default behavior https://eng.ms/docs/products/onebranch/securitycompliancegovernanceandpolicies/sdlforcontainerizedworkflows

### CODE REVIEW

**Review by vishiy — DISMISSED** [review]

**Comment by gracewehner** [comment]
Thanks Soham, do we need to add credscan too? https://eng.ms/docs/microsoft-security/microsoft-threat-protection-mtp/cloud-and-enterprise-security-cesec/security-integration/guardian-wiki/sdl-azdo-extension/credscan-azure-devops-build-task

**Comment by Sohamdg081992** [comment]
> credscan

Thanks Grace! We already have credscan added in the build pipeline.

**Comment by gracewehner** [comment]
> > credscan
> 
> Thanks Grace! We already have credscan added in the build pipeline https://github.com/Azure/prometheus-collector/blob/main/.pipelines/azure-pipeline-build.yml#L151.

You're right, I missed this. Thanks Soham!

**Comment by Sohamdg081992** [comment]
> > > credscan
> > 
> > 
> > Thanks Grace! We already have credscan added in the build pipeline https://github.com/Azure/prometheus-collector/blob/main/.pipelines/azure-pipeline-build.yml#L151.
> 
> You're right, I missed this. Thanks Soham!

Thanks Grace!

**Comment by Sohamdg081992** [comment]
I fixed couple of bugs here. 
1. Removed anti-malware build task from linux since it is only for windows agents
2. Fixed line break bug(powershell) in lifecycle attach for windows

**Review by gracewehner — APPROVED** [review]

**Pull request merged**
